apiVersion: v1
kind: Secret
metadata:
  name: airflow-secrets
  labels:
    app: airflow
type: Opaque
data:
  fernet_key: <BASE64_ENCODED_FERNET_KEY>
  postgres_password: <BASE64_ENCODED_POSTGRES_PASSWORD>
