apiVersion: v1
kind: ConfigMap
metadata:
  name: airflow-config
  labels:
    app: airflow
data:
  airflow.cfg: |
    [core]
    dags_folder = /usr/local/airflow/dags
    executor = KubernetesExecutor
    load_examples = False
    base_log_folder = /usr/local/airflow/logs
    logging_level = INFO

    [logging]
    remote_logging = False
    logging_level = INFO
